spring.application.name=mini-crm-academico

server.port=8080

spring.profiles.active=dev

logging.level.com.etitc.crm=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration

spring.thymeleaf.cache=false